### ISSUE TITLE
does not build/run on OSX (M1 => darwin-arm64)

### ISSUE THREAD

**Issue by mloepfe** [hyperledger/aries-toolbox#218]
I tried to get the toolkit building and running on my M1 MacBookPro without success.

When I clone the repo and run 'yarn install' I get an error message:

HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip

When I change the Version for electron in packages.json to "electron": "^13.0.0" yarn install runs fine.
When I then run yarn run build, it build also fine except that the signing fails. yarn run dev fails.
When I run the built toolkit I only get a white/blank/empty window.

Any ideas how to get this running on Apple-silicon?

**Comment by dbluhm** [comment]
Unfortunately, I don't have any leads on this (not an M1 Mac user). I think we've got someone on our team here at Indicio that might be able to spend a bit of time looking into this but I wouldn't count on this being fixed in the near future, unfortunately.

**Comment by mloepfe** [comment]
If it is an option for you to upgrade to a newer version of electron (one that supports M1) and you can confirm that it works fine (on 'normal' systems), I could check it out on M1 and if there are Problems, try to find out why.

**Comment by froissant** [comment]
This is working fine on my M1 Mac.

**Comment by dbluhm** [comment]
Thanks for the info @froissant; I suspect this was fixed with our recent upgrade to Electron 12. Closing as fixed!
