### ISSUE TITLE
Base64 decode method cuts of json

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-toolbox#222]
I'm working on aries toolbox for AFJ, and I'm running into a weird problem with decoding the base64 invitation from the URL.

I have the following invitation:

```
https://7f5d4521a52a.ngrok.io/invitation?c_i=eyJAdHlwZSI6Imh0dHBzOi8vZGlkY29tbS5vcmcvY29ubmVjdGlvbnMvMS4wL2ludml0YXRpb24iLCJAaWQiOiJmNWI0M2Q5Zi1hOWQ5LTQxYTktOGU5OS1kMTA1YjFlMTUwMTEiLCJsYWJlbCI6IkFyaWVzIEZyYW1ld29yayBKYXZhU2NyaXB0IE1lZGlhdG9yIiwicmVjaXBpZW50S2V5cyI6WyJCRDVVVDlZTFZKbzZvN3BYN0ZVZXBtdUE2WFVmbnVKb29neDlwYWoxZUJGIl0sInNlcnZpY2VFbmRwb2ludCI6Imh0dHBzOi8vN2Y1ZDQ1MjFhNTJhLm5ncm9rLmlvIiwicm91dGluZ0tleXMiOltdfQ
```

If i remove take the `c_i` value and decode it, I get the following output (checked on e.g. https://www.base64decode.org/):

```
{"@type":"https://didcomm.org/connections/1.0/invitation","@id":"f5b43d9f-a9d9-41a9-8e99-d105b1e15011","label":"Aries Framework JavaScript Mediator","recipientKeys":["BD5UT9YLVJo6o7pX7FUepmuA6XUfnuJoogx9paj1eBF"],"serviceEndpoint":"https://7f5d4521a52a.ngrok.io","routingKeys":[]}
```

However when I use this invitation in the toolbox (on the startup screen to create a connection with the agent that you want to control) it gives an error. 

![image](https://user-images.githubusercontent.com/23165168/126002187-0e5aa60f-8cc7-473d-811c-ddc95db9ae1d.png)

After some digging it cuts off the JSON at the base64 decode step. It correctly extracts the following base64 invitation from the URL:

```
eyJAdHlwZSI6Imh0dHBzOi8vZGlkY29tbS5vcmcvY29ubmVjdGlvbnMvMS4wL2ludml0YXRpb24iLCJAaWQiOiJmNWI0M2Q5Zi1hOWQ5LTQxYTktOGU5OS1kMTA1YjFlMTUwMTEiLCJsYWJlbCI6IkFyaWVzIEZyYW1ld29yayBKYXZhU2NyaXB0IE1lZGlhdG9yIiwicmVjaXBpZW50S2V5cyI6WyJCRDVVVDlZTFZKbzZvN3BYN0ZVZXBtdUE2WFVmbnVKb29neDlwYWoxZUJGIl0sInNlcnZpY2VFbmRwb2ludCI6Imh0dHBzOi8vN2Y1ZDQ1MjFhNTJhLm5ncm9rLmlvIiwicm91dGluZ0tleXMiOltdfQ
```

However after the base64 decode the following is returned (see the end missing in the JSON):

```
{"@type":"https://didcomm.org/connections/1.0/invitation","@id":"f5b43d9f-a9d9-41a9-8e99-d105b1e15011","label":"Aries Framework JavaScript Mediator","recipientKeys":["BD5UT9YLVJo6o7pX7FUepmuA6XUfnuJoogx9paj1eBF"],"serviceEndpoint":"https://7f5d4521a52a.ngrok.io","routingKeys":[]
```

It seems like something is mixed up in the base64 decoding, but it's not happening for ACA-Py invitations. I see there is a custom base64 implementation. Is there a specific reason you chose this over an existing library? Not sure what's happening here.

Any insights? Thanks!

**Comment by TimoGlastra** [comment]
Could this be something to do with padded and unpadded base64?

**Comment by swcurran** [comment]
The Aries RFC says the recipient should handle both padded and unpadded base64 encoded data. Does that help?

**Comment by swcurran** [comment]
Sorry...MUST handle padded and unpadded base64 encoded data.

**Comment by TimoGlastra** [comment]
Ah, I thought it was a SHOULD. So we should definitely update the toolbox to support both. 

@dbluhm are you okay to replace the custom base64 implementation with a library that handles both?

**Comment by dbluhm** [comment]
I recently attempted a fix so both padded and unpadded base64 could be accepted by the toolbox. My testing seemed to indicate that it was working correctly but there's a definite chance I botched it. Happy to go with a library to handle this.
