### ISSUE TITLE
Send Message Connection (and other) dropdowns doesn't show list of connections, can't be used

### ISSUE THREAD

**Issue by swcurran** [hyperledger/aries-toolbox#228]
When trying to message between two connected agents, I don't see the names of the connected agents in the drop down - instead I get some unicode text that I can't select.  See screenshot.

![image](https://user-images.githubusercontent.com/1018050/131221490-4f83cca2-3b14-44b5-9e99-8437033177df.png)

Steps done:

I'm running the toolkit and plugins from the main branches of the repo, with the toolkit on Windows 10.   I'm using the Alice and Bob docker file in the Plugin `demo` folder.

- Started the toolbox and agents
- Added Alice and Bob to the Toolbox via the invitations
- Confirmed Discover Features
- Alice created an invitation for Bob, copied it
- Bob pasted in the invitation and processed it.
- Connected
- Went to messages (either agent) and tried to select the other to send the message

Any advice on what is happening?

**Comment by swcurran** [comment]
Looks like it is happening on all of the Select dropdowns.  I have a screenshot from @dbluhm in a tutorial he's done that shows the same issue, so looks like others are having it as well.

**Comment by dbluhm** [comment]
Are you using a recent version of the toolbox? The "Connections [New]" and "Invitations New" was in a commit close to a year old now. The version confusion may have been caused by some out of date instructions in that tutorial (apologies); using Hyperledger main of the toolbox and toolbox plugin repos should be functional today.

**Comment by swcurran** [comment]
Pretty sure I was using main on both, but I'll rerun and report back.

**Comment by swcurran** [comment]
Yup...old code.  Sorry about that.  Thanks for the quick response. Closing.
