### ISSUE TITLE
Update electron to version 12

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-toolbox#237]
Due to a Lets Encrypt certificate that expired on 30 september, I'm not able to use the toolbox anymore with our agents. 

When creating a connection it will fail, stating that the certificate has expired. This is not true, but happens due to a conflict of configurations/processing between client and server. I'll try to update our servers to bypass this bug, but there's also a fix in electron: https://github.com/electron/electron/issues/31212

The latest version that they backported the fix to is electron 12. The toolbox is currently at electron 9.

https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

![image](https://user-images.githubusercontent.com/23165168/135540290-85dd61f8-2376-4192-93ef-927c6230ac19.png)

**Comment by dbluhm** [comment]
I spent a considerable amount of time looking into this issue this past Friday. My findings so far show there are significant challenges to overcome to update to electron 12, I believe primarily stemming from updated security defaults (`contextIsolation` is now enabled by default). Even after setting these security settings back to the original values (which is not recommended), the toolbox was showing just as a blank window.

I'll be the first to admit that I am not an experienced NodeJS/Electron developer so it's very possible I missed something simple. However, it seems we are in need of a significant refactoring to address security concerns even if we can discover a quick fix. We're putting together some thoughts at Indicio on how we can address some of these issues.

**Comment by dbluhm** [comment]
Yeah, these are our exact thoughts as well lol. My plan in the short-term is to prepare a workaround for at least the demo scripts in the toolbox plugin so we can start discussing the long-term solution. CC @JamesKEbert

**Comment by oznfc** [comment]
I also have this error. Anyone have any fixes or workarounds?

**Comment by TimoGlastra** [comment]
If you have access to the server, you can fix it server side:

1. Use HTTP instead of HTTPS, which is definitely not a good solution
2. Depending on what you use the create the SSL certificate you can provide a preferred chain option to use `ISRG Root X1` over `DST Root CA X3` by default ( https://github-wiki-see.page/m/acmesh-official/acme.sh/wiki/Preferred-Chain)

**Comment by oznfc** [comment]
I solved but ı cant see all menu items. I can see only 4 item(Discover Features - Compose - Message History - Trusted Issuers ).

**Comment by TimoGlastra** [comment]
When that happens to me it is often that the connection doesn't have the right permission. When creating an invitation in ACA-Py did you add the following to the create-invitation body?

```json
{
  "metadata": {
    "group": "admin"
  }
}
```

**Comment by oznfc** [comment]
I solved by change socket ssl error.

**Comment by dbluhm** [comment]
This should now be fixed thanks to #252; please feel free to open another issue if you run into any other problems.
